import {StorageService} from '../services/storage';
import React, { useEffect, useState } from 'react';
import { SaasApi } from '../services/api';
import type { User, Product } from '../types';

type Case = {inspection_id:string;severity:string;id:string;title:string;owner_id:string;due_at:string;state:string;containment:string;root_cause:string;action:string;verification:string;version:number};
type Task = {priority:string;started_at:string|null;case_id?:string;inspection_id?:string;id:string;title:string;owner_id:string;due_at:string;completed_at:string;product_id?:string};
type Approval = {inspection_id:string;session_code:string;operator_name:string;status:string;reason:string};
type Notification = {id:number;title:string;kind:string;entity_id:string;read_at:string};
type Work = {summary?:{open_cases:number;overdue_tasks:number;pending_approvals:number};cases:Case[];tasks:Task[];approvals:Approval[];notifications:Notification[]};
const states:Record<string,string>={open:'Açık',action:'Aksiyon',verification:'Doğrulama',closed:'Kapalı',pending:'Onay bekliyor',approved:'Onaylandı',rejected:'Reddedildi'};
const field='mt-1 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm';
const button='rounded-lg bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50';
const dateInput=(date:string)=>{const value=new Date(date);return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);};

export function WorkCenter({users,products,currentUser,onInspect,section,onSectionChange,onOpenRecord}:{onOpenRecord?:(id:string)=>void;section:string;onSectionChange:(section:string)=>void;users:User[];products:Product[];currentUser:User;onInspect:(productId:string)=>void}) {
  const [data,setData]=useState<Work>({cases:[],tasks:[],approvals:[],notifications:[]});
  const [selected,setSelected]=useState<Case|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const tab=section;
  const setTab=onSectionChange;
  const [audit,setAudit]=useState<Record<string,unknown>[]>([]);
  const [organization,setOrganization]=useState<{plants:{id:string;name:string}[];departments:{id:string;plant_id:string;name:string}[];stations:{id:string;department_id:string;name:string}[]}>({plants:[],departments:[],stations:[]});
  const manager=['admin','quality_engineer'].includes(currentUser.role);
  const reload=async()=>setData(await SaasApi.work() as Work);
  const run=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await action();await reload();}catch(error){setError(error instanceof Error?error.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}};
  useEffect(()=>{void reload().catch(error=>setError(String(error)));const timer=setInterval(()=>void reload().catch(()=>{}),30000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(section==='audit')void run(async()=>setAudit(await SaasApi.auditLogs() as Record<string,unknown>[]));if(section==='organization')void run(async()=>setOrganization(await SaasApi.organization() as typeof organization));},[section]);
  const overdue=data.summary?.overdue_tasks??data.tasks.filter(task=>!task.completed_at && new Date(task.due_at).getTime()<Date.now()).length;
  return <div className="space-y-4">
    {['cases','tasks','approvals'].includes(tab)&&<><div className="grid grid-cols-3 gap-3">{[['Açık uygunsuzluk',data.summary?.open_cases??data.cases.filter(c=>c.state!=='closed').length],['Bekleyen onay',data.summary?.pending_approvals??data.approvals.filter(a=>a.status==='pending').length],['Geciken görev',overdue]].map(([label,value])=><div key={label} className="quality-card"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>)}</div><div className="flex gap-2" aria-label="Aksiyon kategorileri">{[['cases','Uygunsuzluklar'],['tasks','Görevler'],...(currentUser.role==='operator'?[]:[['approvals','Onaylar']])].map(([id,label])=><button key={id} type="button" aria-pressed={tab===id} className={tab===id?'quality-primary':'quality-secondary'} onClick={()=>setTab(id)}>{label}</button>)}</div></>}
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
    {tab==='inbox'&&<div className="space-y-2">{!data.notifications.length&&<p>Yeni bildirim yok.</p>}{data.notifications.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-4"><button className="text-left" type="button" onClick={()=>{setTab(item.kind==='ncr'?'cases':item.kind==='task'?'tasks':'approvals');if(item.kind==='ncr')setSelected(data.cases.find(c=>c.id===item.entity_id)||null);}}>{!item.read_at&&'● '}{item.title}</button>{!item.read_at&&<button disabled={busy} className="rounded-lg border p-3 text-sm" onClick={()=>void run(()=>SaasApi.readNotification(item.id))}>Okundu</button>}</div>)}</div>}
    {tab==='cases'&&<div className="space-y-3">
      {!data.cases.length&&<p>Uygunsuzluk bulunmuyor. NOK kaydı oluştuğunda otomatik açılır.</p>}
      {data.cases.map(item=><button key={item.id} onClick={()=>setSelected(item)} className="flex w-full flex-wrap justify-between gap-2 rounded-xl border bg-white p-4 text-left"><span>{item.title} · {{critical:'Kritik',major:'Önemli',minor:'Düşük'}[item.severity]||'Önemli'}</span><span>{states[item.state]} · {users.find(user=>user.id===item.owner_id)?.name||'Sorumlu atanmadı'}</span></button>)}
      {selected&&<form key={selected.id+':'+selected.version} className="space-y-3 rounded-xl border bg-white p-5" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void run(async()=>{const updated=await SaasApi.updateCase(selected.id,{version:selected.version,severity:fields.get('severity'),ownerId:fields.get('ownerId'),dueAt:new Date(String(fields.get('dueAt'))).toISOString(),state:fields.get('state'),containment:fields.get('containment'),rootCause:fields.get('rootCause'),action:fields.get('action'),verification:fields.get('verification')});setSelected(updated as Case);});}}>
        <h3 className="font-bold">{selected.title}</h3>{onOpenRecord&&<button type="button" className="quality-secondary" onClick={()=>onOpenRecord(selected.inspection_id)}>Kaynak ölçümü aç</button>}<fieldset disabled={busy||selected.state==='closed'||currentUser.role==='auditor'} className="space-y-3">
          <label className="block text-sm">Önem seviyesi<select name="severity" defaultValue={selected.severity||'major'} className={field}><option value="minor">Düşük</option><option value="major">Önemli</option><option value="critical">Kritik</option></select></label>
          <label className="block text-sm">Sorumlu<select required name="ownerId" defaultValue={selected.owner_id||''} className={field}><option value="">Seçin</option>{users.filter(user=>user.status==='active').map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label>
          <label className="block text-sm">Termin<input required name="dueAt" type="datetime-local" defaultValue={selected.due_at?dateInput(selected.due_at):''} className={field}/></label>
          {[['containment','Geçici önlem',selected.containment],['rootCause','Kök neden',selected.root_cause],['action','Düzeltici aksiyon',selected.action],['verification','Doğrulama ve kapanış kanıtı',selected.verification]].map(([name,label,value])=><label key={name} className="block text-sm">{label}<textarea name={name} defaultValue={value} maxLength={5000} className={field}/></label>)}
          <label className="block text-sm">Aşama<select name="state" defaultValue={selected.state} className={field}>{['open','action','verification','closed'].map(state=><option key={state} value={state}>{states[state]}</option>)}</select></label>
          <p className="text-xs text-slate-500">Kapatma, aksiyon sorumlusundan farklı bir kalite yetkilisinin doğrulamasını gerektirir.</p><button className={button}>Kaydet</button>
        </fieldset>
      </form>}
    </div>}
    {tab==='tasks'&&<div className="space-y-3">{!data.tasks.length&&<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">Henüz atanmış görev yok.</p>}
      {manager&&<form className="grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);void run(async()=>{await SaasApi.createTask({title:fields.get('title'),ownerId:fields.get('ownerId'),productId:fields.get('productId')||undefined,priority:fields.get('priority'),caseId:fields.get('caseId')||undefined,inspectionId:fields.get('inspectionId')||undefined,dueAt:new Date(String(fields.get('dueAt'))).toISOString()});form.reset();});}}>
        <label>Görev<input required name="title" minLength={3} maxLength={250} className={field}/></label><label>Sorumlu<select required name="ownerId" className={field}><option value="">Seçin</option>{users.filter(u=>u.status==='active').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
        <label>Kaynak ölçüm<select name="inspectionId" className={field}><option value="">Seçilmedi</option>{StorageService.getInspectionLogs().map(l=><option key={l.id} value={l.id}>{l.sessionCode} · {l.productCode}</option>)}</select></label><label>Öncelik<select name="priority" defaultValue="normal" className={field}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Yüksek</option><option value="critical">Kritik</option></select></label><label>Kaynak uygunsuzluk<select name="caseId" className={field}><option value="">Seçilmedi</option>{data.cases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Ürün<select name="productId" className={field}><option value="">Genel görev</option>{products.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select></label><label>Termin<input required name="dueAt" type="datetime-local" className={field}/></label><button disabled={busy} className={button}>Görev ata</button>
      </form>}
      {data.tasks.map(task=><div key={task.id} className="space-y-2 rounded-xl border bg-white p-4"><h3 className="font-bold">{task.title} · {{low:'Düşük',normal:'Normal',high:'Yüksek',critical:'Kritik'}[task.priority]||'Normal'}</h3>{task.case_id&&<button className="text-sm text-blue-700" onClick={()=>{setSelected(data.cases.find(c=>c.id===task.case_id)||null);setTab('cases');}}>Kaynak uygunsuzluğu aç</button>}{task.inspection_id&&onOpenRecord&&<button className="text-sm text-blue-700" onClick={()=>onOpenRecord(task.inspection_id!)}>Kaynak ölçümü aç</button>}<p>{users.find(u=>u.id===task.owner_id)?.name} · {new Date(task.due_at).toLocaleString('tr-TR')} · {task.completed_at?'Tamamlandı':new Date(task.due_at).getTime()<Date.now()?'Gecikti':task.started_at?'Devam Ediyor':'Açık'}</p>{!task.completed_at&&currentUser.role!=='auditor'&&<div className="flex flex-wrap gap-2">{!task.started_at&&<button disabled={busy} className="quality-secondary" onClick={()=>void run(()=>SaasApi.startTask(task.id))}>Başlat</button>}{task.product_id&&<button className={button} onClick={()=>onInspect(task.product_id!)}>Kontrol başlat</button>}<button disabled={busy} className="rounded-lg border p-3" onClick={()=>{const note=prompt('Tamamlama notu (en az 5 karakter)');if(note)void run(()=>SaasApi.completeTask(task.id,note));}}>Tamamla</button></div>}</div>)}
    </div>}
    {tab==='approvals'&&<div className="space-y-3">{!data.approvals.length&&<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">İncelenecek ölçüm bulunmuyor.</p>}{data.approvals.map(item=><div key={item.inspection_id} className="space-y-2 rounded-xl border bg-white p-4"><p className="font-bold">{item.session_code} · {states[item.status]}</p><p>{item.operator_name} · {item.reason}{item.status==='pending'&&' · Ölçümü yapan kişi dışındaki Yönetici / Kalite Uzmanı onayı bekleniyor.'}</p>{manager&&item.status==='pending'&&<div className="flex gap-2">{(['approved','rejected'] as const).map(status=><button disabled={busy} key={status} className={status==='approved'?button:'rounded-lg bg-red-700 p-3 text-white'} onClick={()=>{const reason=prompt('Karar gerekçesi (en az 5 karakter)');if(reason)void run(()=>SaasApi.reviewInspection(item.inspection_id,status,reason));}}>{status==='approved'?'Onayla':'Reddet / yeniden kontrol'}</button>)}</div>}</div>)}</div>}
    {tab==='audit'&&<div className="space-y-2"><p className="text-sm">Son 500 olay; değişiklik öncesi ve sonrası kayıtları.</p>{audit.map(item=><details key={String(item.id)} className="rounded-xl border bg-white p-4"><summary>{String(item.created_at)} · {String(item.actor_name||'Sistem')} · {String(item.action)}</summary><div className="mt-3 grid gap-3 md:grid-cols-2"><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">Önce: {JSON.stringify(item.before_data,null,2)}</pre><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">Sonra: {JSON.stringify(item.after_data,null,2)}</pre></div></details>)}</div>}
    {tab==='organization'&&<div className="space-y-3"><form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void run(async()=>{await SaasApi.createOrganization({name:fields.get('name'),plantId:fields.get('plantId')||undefined,departmentId:fields.get('departmentId')||undefined});setOrganization(await SaasApi.organization() as typeof organization);});}}><label>Ad<input required name="name" minLength={2} className={field}/></label><label className="block">Bağlı tesis<select name="plantId" className={field}><option value="">Yeni tesis oluştur</option>{organization.plants.map(plant=><option key={plant.id} value={plant.id}>{plant.name}</option>)}</select></label><label className="block">Bağlı bölüm (istasyon eklemek için)<select name="departmentId" className={field}><option value="">Bölüm seçilmedi</option>{organization.departments.map(d=><option key={d.id} value={d.id}>{organization.plants.find(p=>p.id===d.plant_id)?.name} · {d.name}</option>)}</select></label><button disabled={busy} className={button}>Ekle</button></form>{organization.plants.map(plant=><div key={plant.id} className="rounded-xl border bg-white p-4"><h3 className="font-bold">{plant.name}</h3><ul className="ml-3 border-l border-slate-200 pl-4">{organization.departments.filter(d=>d.plant_id===plant.id).map(d=><li key={d.id} className="py-2"><details open><summary>{d.name}</summary><ul className="ml-3 border-l border-slate-200 pl-4">{organization.stations.filter(st=>st.department_id===d.id).map(st=><li className="py-2 text-sm text-slate-600" key={st.id}>{st.name}</li>)}</ul></details></li>)}</ul></div>)}</div>}
  </div>;
}
