import {NotificationList} from './NotificationList';
import {AuditLog} from './AuditLog';
import {Button, Card, MetricCard, DataTable, Badge, StatusBadge, Tabs, DetailDrawer, Modal, Field, Textarea, PageActions, TraceTimeline, EmptyState} from './ui';
import {StorageService} from '../services/storage';
import React, { useEffect, useState } from 'react';
import { SaasApi } from '../services/api';
import type { User, Product } from '../types';

type Case = {inspection_id:string;severity:string;id:string;title:string;owner_id:string;due_at:string;state:string;containment:string;root_cause:string;action:string;verification:string;version:number};
type Task = {priority:string;started_at:string|null;case_id?:string;inspection_id?:string;id:string;title:string;owner_id:string;due_at:string;completed_at:string;product_id?:string};
type Approval = {inspection_id:string;session_code:string;operator_name:string;status:string;reason:string};
type Notification = {id:number;title:string;kind:string;entity_id:string;read_at:string};
type Work = {summary?:{open_cases:number;overdue_tasks:number;pending_approvals:number};cases:Case[];tasks:Task[];approvals:Approval[];notifications:Notification[]};
const states:Record<string,string>={open:'Açık',action:'Aksiyon',verification:'Doğrulama',closed:'Kapalı',pending:'Onay bekliyor',approved:'Onaylandı',rejected:'Reddedildi'};
const field='rq-input mt-1';
const button='rounded-lg bg-blue-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50';
const dateInput=(date:string)=>{const value=new Date(date);return new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);};

export function WorkCenter({users,products,currentUser,onInspect,section,onSectionChange,onOpenRecord}:{onOpenRecord?:(id:string)=>void;section:string;onSectionChange:(section:string)=>void;users:User[];products:Product[];currentUser:User;onInspect:(productId:string)=>void}) {
  const [data,setData]=useState<Work>({cases:[],tasks:[],approvals:[],notifications:[]});
  const [selected,setSelected]=useState<Case|null>(null);
  const [decision,setDecision]=useState<{kind:'task'|'approved'|'rejected';id:string}|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const tab=section;
  const setTab=onSectionChange;
  const [audit,setAudit]=useState<Record<string,unknown>[]>([]);
  const [organization,setOrganization]=useState<{plants:{id:string;name:string}[];departments:{id:string;plant_id:string;name:string}[];stations:{id:string;department_id:string;name:string}[]}>({plants:[],departments:[],stations:[]});
  const manager=['admin','quality_engineer'].includes(currentUser.role);
  const reload=async()=>setData(await SaasApi.work() as Work);
  const run=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await action();await reload();}catch(error){setError(error instanceof Error?error.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}};
  useEffect(()=>{void reload().catch(error=>setError(String(error)));const timer=setInterval(()=>void reload().catch(()=>{}),30000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(section==='audit')void run(async()=>setAudit(await SaasApi.auditLogs() as Record<string,unknown>[]));if(section==='organization')void run(async()=>setOrganization(await SaasApi.organization() as typeof organization));},[section]);
  const overdue=data.summary?.overdue_tasks??data.tasks.filter(task=>!task.completed_at && new Date(task.due_at).getTime()<Date.now()).length;
  return <div className="space-y-4">
    {['cases','tasks','approvals'].includes(tab)&&<><div className="rq-metrics-row"><MetricCard label="Açık uygunsuzluk" value={data.summary?.open_cases??data.cases.filter(c=>c.state!=='closed').length} tone="danger"/><MetricCard label="Bekleyen onay" value={data.summary?.pending_approvals??data.approvals.filter(a=>a.status==='pending').length} tone="warning"/><MetricCard label="Geciken görev" value={overdue} tone={overdue?'danger':'neutral'}/></div><Tabs label="Aksiyon kategorileri" value={tab} onChange={setTab} items={[{id:'cases',label:'Uygunsuzluklar'},{id:'tasks',label:'Görevler'},...(currentUser.role==='operator'?[]:[{id:'approvals',label:'Onaylar'}])]}/></>}
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
    {tab==='inbox'&&<NotificationList items={data.notifications} busy={busy} onOpen={item=>{setTab(item.kind==='ncr'?'cases':item.kind==='task'?'tasks':'approvals');if(item.kind==='ncr')setSelected(data.cases.find(c=>c.id===data.notifications.find(n=>n.id===item.id)?.entity_id)||null);}} onRead={item=>void run(()=>SaasApi.readNotification(item.id))}/>}
    {tab==='cases'&&<div className="space-y-3">
      {!data.cases.length&&<p>Uygunsuzluk bulunmuyor. NOK kaydı oluştuğunda otomatik açılır.</p>}
      {!!data.cases.length&&<DataTable className="rq-mobile-cards" label="Uygunsuzluk kayıtları"><thead><tr><th>Uygunsuzluk / kaynak</th><th>Önem</th><th>Aşama</th><th>Sorumlu</th><th>Termin</th><th>İşlem</th></tr></thead><tbody>{data.cases.map(item=>{const record=StorageService.getInspectionLogs().find(log=>log.id===item.inspection_id);return <tr key={item.id}><td><button className="rq-row-link" onClick={()=>setSelected(item)}>{item.title}</button>{record&&<small>{record.productCode} · {record.lotNumber||'Parti belirtilmedi'} · {record.machineNo}</small>}</td><td><Badge tone={item.severity==='critical'?'danger':item.severity==='major'?'warning':'neutral'}>{{critical:'Kritik',major:'Önemli',minor:'Düşük'}[item.severity]||item.severity}</Badge></td><td><Badge tone={item.state==='closed'?'success':'warning'}>{states[item.state]}</Badge></td><td>{users.find(user=>user.id===item.owner_id)?.name||'Sorumlu atanmadı'}</td><td className="rq-technical">{item.due_at?new Date(item.due_at).toLocaleString('tr-TR'):'—'}</td><td><Button onClick={()=>setSelected(item)}>İncele</Button></td></tr>;})}</tbody></DataTable>}
      <DetailDrawer open={!!selected} title={selected?.title||'Uygunsuzluk'} busy={busy} onClose={()=>setSelected(null)}>{selected&&<form key={selected.id+':'+selected.version} className="space-y-5" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void run(async()=>{const updated=await SaasApi.updateCase(selected.id,{version:selected.version,severity:fields.get('severity'),ownerId:fields.get('ownerId'),dueAt:new Date(String(fields.get('dueAt'))).toISOString(),state:fields.get('state'),containment:fields.get('containment'),rootCause:fields.get('rootCause'),action:fields.get('action'),verification:fields.get('verification')});setSelected(updated as Case);});}}>
        <div className="rq-summary"><Badge tone={selected.state==='closed'?'success':'warning'}>{states[selected.state]}</Badge><span>Revizyon {selected.version}</span></div><TraceTimeline items={[{id:'containment',title:'Geçici önlem',detail:selected.containment},{id:'root',title:'Kök neden',detail:selected.root_cause},{id:'action',title:'Düzeltici aksiyon',detail:selected.action},{id:'verification',title:'Doğrulama',detail:selected.verification}].filter(item=>!!item.detail)}/>{onOpenRecord&&<Button type="button" className="quality-secondary" onClick={()=>onOpenRecord(selected.inspection_id)}>Kaynak ölçümü aç</Button>}<fieldset disabled={busy||selected.state==='closed'||currentUser.role==='auditor'} className="space-y-3">
          <label className="block text-sm">Önem seviyesi<select name="severity" defaultValue={selected.severity||'major'} className={field}><option value="minor">Düşük</option><option value="major">Önemli</option><option value="critical">Kritik</option></select></label>
          <label className="block text-sm">Sorumlu<select required name="ownerId" defaultValue={selected.owner_id||''} className={field}><option value="">Seçin</option>{users.filter(user=>user.status==='active').map(user=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label>
          <label className="block text-sm">Termin<input required name="dueAt" type="datetime-local" defaultValue={selected.due_at?dateInput(selected.due_at):''} className={field}/></label>
          {[['containment','Geçici önlem',selected.containment],['rootCause','Kök neden',selected.root_cause],['action','Düzeltici aksiyon',selected.action],['verification','Doğrulama ve kapanış kanıtı',selected.verification]].map(([name,label,value])=><label key={name} className="block text-sm">{label}<textarea name={name} defaultValue={value} maxLength={5000} className={field}/></label>)}
          <label className="block text-sm">Aşama<select name="state" defaultValue={selected.state} className={field}>{['open','action','verification','closed'].map(state=><option key={state} value={state}>{states[state]}</option>)}</select></label>
          <p className="text-xs text-slate-500">Kapatma, aksiyon sorumlusundan farklı bir kalite yetkilisinin doğrulamasını gerektirir.</p><Button type="submit" variant="primary" className={button}>Kaydet</Button>
        </fieldset>
      </form>}</DetailDrawer>
    </div>}
    {tab==='tasks'&&<div className="space-y-3">{!data.tasks.length&&<p className="rounded-xl border bg-white p-6 text-sm text-slate-500">Henüz atanmış görev yok.</p>}
      {manager&&<details className="rq-card"><summary className="rq-section-title cursor-pointer">Yeni görev ata</summary><form className="rq-form-grid mt-4" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);void run(async()=>{await SaasApi.createTask({title:fields.get('title'),ownerId:fields.get('ownerId'),productId:fields.get('productId')||undefined,priority:fields.get('priority'),caseId:fields.get('caseId')||undefined,inspectionId:fields.get('inspectionId')||undefined,dueAt:new Date(String(fields.get('dueAt'))).toISOString()});form.reset();});}}>
        <label>Görev<input required name="title" minLength={3} maxLength={250} className={field}/></label><label>Sorumlu<select required name="ownerId" className={field}><option value="">Seçin</option>{users.filter(u=>u.status==='active').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label>
        <label>Kaynak ölçüm<select name="inspectionId" className={field}><option value="">Seçilmedi</option>{StorageService.getInspectionLogs().map(l=><option key={l.id} value={l.id}>{l.sessionCode} · {l.productCode}</option>)}</select></label><label>Öncelik<select name="priority" defaultValue="normal" className={field}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Yüksek</option><option value="critical">Kritik</option></select></label><label>Kaynak uygunsuzluk<select name="caseId" className={field}><option value="">Seçilmedi</option>{data.cases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Ürün<select name="productId" className={field}><option value="">Genel görev</option>{products.map(p=><option key={p.id} value={p.id}>{p.code}</option>)}</select></label><label>Termin<input required name="dueAt" type="datetime-local" className={field}/></label><Button type="submit" variant="primary" disabled={busy} className={button}>Görev ata</Button>
      </form></details>}
      {!!data.tasks.length&&<DataTable className="rq-mobile-cards" label="Atanmış görevler"><thead><tr><th>Görev / ilişkiler</th><th>Öncelik</th><th>Sorumlu</th><th>Termin</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody>{data.tasks.map(task=>{const late=!task.completed_at&&new Date(task.due_at).getTime()<Date.now();return <tr key={task.id} className={late?'rq-row-alert':''}><td><strong>{task.title}</strong>{task.product_id&&<small>{products.find(p=>p.id===task.product_id)?.code}</small>}<div className="rq-inline-links">{task.case_id&&<Button variant="ghost" onClick={()=>{setSelected(data.cases.find(c=>c.id===task.case_id)||null);setTab('cases');}}>Uygunsuzluk</Button>}{task.inspection_id&&onOpenRecord&&<Button variant="ghost" onClick={()=>onOpenRecord(task.inspection_id!)}>Kaynak ölçüm</Button>}</div></td><td><Badge tone={task.priority==='critical'?'danger':task.priority==='high'?'warning':'neutral'}>{{low:'Düşük',normal:'Normal',high:'Yüksek',critical:'Kritik'}[task.priority]||task.priority}</Badge></td><td>{users.find(u=>u.id===task.owner_id)?.name||'Atanmadı'}</td><td className="rq-technical">{new Date(task.due_at).toLocaleString('tr-TR')}</td><td><Badge tone={task.completed_at?'success':late?'danger':'info'}>{task.completed_at?'Tamamlandı':late?'Gecikti':task.started_at?'Devam ediyor':'Açık'}</Badge></td><td>{!task.completed_at&&currentUser.role!=='auditor'&&<div className="rq-actions">{!task.started_at&&<Button disabled={busy} onClick={()=>void run(()=>SaasApi.startTask(task.id))}>Başlat</Button>}{task.product_id&&<Button onClick={()=>onInspect(task.product_id!)}>Kontrol başlat</Button>}<Button disabled={busy} variant="primary" onClick={()=>setDecision({kind:'task',id:task.id})}>Tamamla</Button></div>}</td></tr>;})}</tbody></DataTable>}
    </div>}
    {tab==='approvals'&&<div className="space-y-4"><p className="rq-helper">Bekleyen ölçümleri inceleyin ve gerekçeli kararınızı kaydedin. Onay, ölçümü yapan kişi dışındaki Yönetici / Kalite Uzmanı tarafından verilir.</p>{!data.approvals.length?<EmptyState title="Onay kuyruğu boş" description="İncelenecek ölçüm geldiğinde burada listelenir."/>:<DataTable className="rq-mobile-cards" label="Ölçüm onay kuyruğu"><thead><tr><th>Ölçüm / ürün</th><th>Plan revizyonu</th><th>Operatör / ölçüm zamanı</th><th>Durum</th><th>Gerekçe</th><th>İşlem</th></tr></thead><tbody>{data.approvals.map(item=>{const record=StorageService.getInspectionLogs().find(log=>log.id===item.inspection_id);return <tr key={item.inspection_id}><td><strong className="rq-technical">{item.session_code}</strong>{record&&<small>{record.productCode} · {record.productName}</small>}</td><td className="rq-technical">{record?.controlPlanVersion||'—'}</td><td>{item.operator_name}{record&&<small>{new Date(record.timestamp).toLocaleString('tr-TR')}</small>}</td><td><Badge tone={item.status==='approved'?'success':item.status==='rejected'?'danger':'warning'}>{states[item.status]}</Badge></td><td>{item.reason||'—'}</td><td><div className="rq-actions">{onOpenRecord&&<Button onClick={()=>onOpenRecord(item.inspection_id)}>Ölçümü incele</Button>}{manager&&item.status==='pending'&&<><Button disabled={busy} variant="primary" onClick={()=>setDecision({kind:'approved',id:item.inspection_id})}>Onayla</Button><Button disabled={busy} variant="danger" onClick={()=>setDecision({kind:'rejected',id:item.inspection_id})}>Reddet / yeniden kontrol</Button></>}</div></td></tr>;})}</tbody></DataTable>}</div>}
    {tab==='audit'&&<AuditLog items={audit}/>}
    {tab==='organization'&&<div className="space-y-3"><form className="space-y-3 rounded-xl border bg-white p-4" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void run(async()=>{await SaasApi.createOrganization({name:fields.get('name'),plantId:fields.get('plantId')||undefined,departmentId:fields.get('departmentId')||undefined});setOrganization(await SaasApi.organization() as typeof organization);});}}><label>Ad<input required name="name" minLength={2} className={field}/></label><label className="block">Bağlı tesis<select name="plantId" className={field}><option value="">Yeni tesis oluştur</option>{organization.plants.map(plant=><option key={plant.id} value={plant.id}>{plant.name}</option>)}</select></label><label className="block">Bağlı bölüm (istasyon eklemek için)<select name="departmentId" className={field}><option value="">Bölüm seçilmedi</option>{organization.departments.map(d=><option key={d.id} value={d.id}>{organization.plants.find(p=>p.id===d.plant_id)?.name} · {d.name}</option>)}</select></label><Button type="submit" disabled={busy} className={button}>Ekle</Button></form>{organization.plants.map(plant=><div key={plant.id} className="rounded-xl border bg-white p-4"><h3 className="font-bold">{plant.name}</h3><ul className="ml-3 border-l border-slate-200 pl-4">{organization.departments.filter(d=>d.plant_id===plant.id).map(d=><li key={d.id} className="py-2"><details open><summary>{d.name}</summary><ul className="ml-3 border-l border-slate-200 pl-4">{organization.stations.filter(st=>st.department_id===d.id).map(st=><li className="py-2 text-sm text-slate-600" key={st.id}>{st.name}</li>)}</ul></details></li>)}</ul></div>)}</div>}
    <Modal className="rq-bottom-sheet" open={!!decision} busy={busy} title={decision?.kind==='task'?'Görevi tamamla':decision?.kind==='approved'?'Ölçümü onayla':'Ölçümü reddet / yeniden kontrol'} onClose={()=>setDecision(null)}>{decision&&<form onSubmit={event=>{event.preventDefault();const note=String(new FormData(event.currentTarget).get('note')||'').trim();if(note.length<5)return;void run(async()=>{if(decision.kind==='task')await SaasApi.completeTask(decision.id,note);else await SaasApi.reviewInspection(decision.id,decision.kind,note);setDecision(null);});}}><Field label="Gerekçe / tamamlama notu" hint="En az 5 karakter."><Textarea name="note" required minLength={5} maxLength={5000} disabled={busy}/></Field>{error&&<p role="alert" className="rq-feedback rq-tone-danger">{error}</p>}<PageActions><Button disabled={busy} onClick={()=>setDecision(null)}>İptal</Button><Button type="submit" variant={decision.kind==='rejected'?'danger':'primary'} loading={busy}>Kararı kaydet</Button></PageActions></form>}</Modal>
  </div>;
}
